Odontogest/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Odontogest.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;

namespace Odontogest.Controllers
{
    public class CategoryController : Controller
    {
        private readonly odontogestContext _context;

        public CategoryController(odontogestContext contex)
        {
            _context = contex;
        }
        // GET: Category
        public ActionResult ListCategory()
        {
           var category = _context.Categories.ToList();
            return View(category);
        }

        // GET: Category/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Category/Create
        public ActionResult CreateCategory(int? id)
        {
            ViewBag.PageName = id == null ? "Create Categori" : "Edit Category";
            ViewBag.isEdit = id == null ? false : true;

            if(id == null)
            {
                return View();
            }
            else
            {
                var categori = _context.Categories.Find(id);

                if(categori == null)
                {
                    NotFound();
                }

                return View(categori);
            }
            
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(int id, [Bind("IdCategory,NameCategory")] Category category)
        {
            bool exist = false;

            Category categorys = _context.Categories.Find(id);

            if(categorys != null)
            {
                exist = true;
            }
            else
            {
                categorys = new Category();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    categorys.NameCategory = category.NameCategory;

                    if (exist)
                    {
                        _context.Update(categorys);
                    }
                    else
                    {
                        _context.Add(category);
                    }
                    
                    _context.SaveChanges();
                    
                }
                catch(DbUpdateConcurrencyException)
                {

                    NotFound();
                }
                return RedirectToAction(nameof(ListCategory));
            }
            return View(category);
            
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Category/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Odontogest/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Odontogest.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Helpers;

namespace Odontogest.Controllers
{
    public class InventoryController : Controller
    {
        private readonly odontogestContext _context;
        private IWebHostEnvironment _enviroment;

        public InventoryController(odontogestContext context)
        {
            _context = context;
            //_enviroment = enviroment;
        }

        
        //public Inventory listInven { get; set; }

        //var listInve = new Inventory();

        private void drownCategori(object selecCategory = null)
        {
            var categoria = from d in _context.Categories
                            orderby d.NameCategory
                            select d;

            ViewBag.IdCategory = new SelectList(categoria.AsNoTracking(),
                nameof(Category.IdCategory),
                nameof(Category.NameCategory),
                selecCategory);
        }
        private void drownStore(object Selectstories = null)
        {
            var stories = from d in _context.Stores
                          orderby d.NameStore
                          select d;

            ViewBag.IdStore = new SelectList(stories.AsNoTracking(),
                nameof(Store.IdStore),
                nameof(Store.NameStore),
                Selectstories);
        }

        

        // GET: Inventory
        public ActionResult ListInventory()
        {
            var listInven = new Inventory();
            drownStore(listInven.FkStore);
            drownCategori(listInven.FkCategory);

            //var inventary = _context.Inventories
            //    .Include(c => c.FkCategoryNavigation)
            //    .Include(s => s.FkStoreNavigation)
            //    .AsNoTracking();

            var inventary = _context.Inventories
            .Select(item => new
            {
                Item = item,
                Category = item.FkCategoryNavigation,
                Store = item.FkStoreNavigation
            })
            .AsNoTracking()
            .ToList()
            .Select(result => result.Item);

            return View(inventary.ToList());
        }

        // GET: Inventory/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Inventory/Create
        public ActionResult AddorEdit(int? id, IFormFile upload)
        {
            ViewBag.PageName = id == null ? "Add Inventory" : "Edit Inventory";
            ViewBag.isExit = id == null ? false : true;
            var listInven = new Inventory();

            if (id == null)
            {
                drownStore(listInven.FkStore);
                drownCategori(listInven.FkCategory);
                return View();
            }
            else
            {
                listInven = _context.Inventories
                    .AsNoTracking()
                    .FirstOrDefault(i => id == i.IdInventory);

                if (listInven == null)
                {
                    NotFound();
                }

                drownStore(listInven.FkStore);
                drownCategori(listInven.FkCategory);
                return View(listInven);
            }

        }

        // POST: Inventory/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddorEdit(int id, [Bind("NameInventory,FkCategory,FkStore,Price,Quantity,Description,Image")]
            Inventory inventory, IFormFile upload)
        {
            
            bool Exits = false;

            string folderpaht = @"wwwroot\Images\Inventory";
            var paht = "";
            var ft = "";


            Inventory inventories = _context.Inventories
                .AsNoTracking()
                .FirstOrDefault(i => id == i.IdInventory);
            

                drownStore(inventory.FkStore);
            drownCategori(inventory.FkCategory);

            if (!Directory.Exists(folderpaht))
            {
                Directory.CreateDirectory(folderpaht);
            }
            
            if (inventories != null)
            {
                Exits = true;
                
            }
            else
            {
                inventories = new Inventory();
            }

            if (ModelState.IsValid)
            {

                if (upload == null)
                {
                    //var ft = _context.Inventories.SingleOrDefault(i => i.IdInventory == inventories.IdInventory).Image;

                    if (inventories.Image == null)
                    {
                        ft = "avatar.PNG";
                    }
                    else
                    {
                        ft = inventories.Image;
                    }

                    

                    paht = @"wwwroot\Images\Inventory\"+ft;
                    

                    using (var str = new FileStream(paht, FileMode.Open, FileAccess.Read))
                    {
                        upload = new FormFile(str, 0, str.Length, ft, ft);

                        inventories.NameInventory = inventory.NameInventory;
                        inventories.FkCategory = inventory.FkCategory;
                        inventories.FkStore = inventory.FkStore;
                        inventories.Price = inventory.Price;
                        inventories.Quantity = inventory.Quantity;
                        inventories.QuantityAvailable = inventory.QuantityAvailable;
                        inventories.Description = inventory.Description;

                        inventories.Image = upload.FileName;

                    }

                    if (Exits)
                    {
                        inventories.DateUpdate = DateTime.Now;
                        _context.Update(inventories);
                    }
                    else
                    {
                        inventories.CreationDate = DateTime.Now;
                        _context.Add(inventories);
                    }

                    _context.SaveChanges();
                    return RedirectToAction(nameof(ListInventory));
                }
                else
                {
                    paht = @"wwwroot\Images\Inventory\"+inventories.Image;
                    var file = Path.Combine(folderpaht, upload.FileName);

                    try
                    {
                        
                        using (var stream = new FileStream(file, FileMode.Create))
                        {
                            upload.CopyTo(stream);

                            inventories.NameInventory = inventory.NameInventory;
                            inventories.FkCategory = inventory.FkCategory;
                            inventories.FkStore = inventory.FkStore;
                            inventories.Price = inventory.Price;
                            inventories.Quantity = inventory.Quantity;
                            inventories.QuantityAvailable = inventory.QuantityAvailable;
                            inventories.Description = inventory.Description;
                            inventories.Image = upload.FileName;

                            ViewBag.image = inventories.Image;

                        }


                        if (Exits)
                        {
                            inventories.DateUpdate = DateTime.Now;
                            _context.Update(inventories);
                        }
                        else
                        {
                            inventories.CreationDate = DateTime.Now;
                            _context.Add(inventories);
                        }

                        _context.SaveChanges();

                    }
                    catch (DbUpdateException)
                    {
                        return View();
                    }

                    return RedirectToAction(nameof(ListInventory));
                }
                
            }

            drownStore(inventory.FkStore);
            drownCategori(inventory.FkCategory);
            return View(inventories);
        }

       
    
                    

        // GET: Inventory/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if(id == null)
        //    {
        //        return NotFound();
        //    }

        //    var inventoris = _context.Inventories
        //            .AsNoTracking()
        //            .FirstOrDefault(i => id == i.IdInventory);

        //    if (inventoris == null)
        //    {
        //        return NotFound();
        //    }
                        
        //    return View(inventoris);
        //}

        // POST: Inventory/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int? id)
        {
            var inventor = _context.Inventories.Find(id);

            try
            {
                _context.Inventories.Remove(inventor);
                _context.SaveChanges();
                ViewBag.Message = "Se Elimino correctamente";
                return RedirectToAction(nameof(ListInventory));
            }
            catch
            {
                return View();
            }
        }
               
    }
}


//inventories.NameInventory = inventory.NameInventory;
//inventories.FkCategory = inventory.FkCategory;
//inventories.FkStore = inventory.FkStore;
//inventories.Price = inventory.Price;
//inventories.Quantity = inventory.Quantity;
//inventories.QuantityAvailable = inventory.QuantityAvailable;
//inventories.Description = inventory.Description;
//inventories.Image = inventory.Image;

Odontogest/Controllers/StoreController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Odontogest.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;

namespace Odontogest.Controllers
{
    
    public class StoreController : Controller
    {
        private readonly odontogestContext _context;
        public StoreController(odontogestContext context) 
        {
            _context = context;
            //_environment = environment;
        }

        
        // GET: Store
        public ActionResult ListStores(string search)
        {
            //var stores = _context.Stores
            //     .Include(c=> c.Inventories)
            //     .AsNoTracking()
            //     .ToList();

            var stores = from s in _context.Stores
                         select s;


            if (!string.IsNullOrEmpty(search))
            {
                stores = stores.Where(s => s.NameStore.Contains(search));
            }

            return View(stores);
        }

  
              // GET: Store/Details/5
        public ActionResult Details(int id)
        {
            var detail = _context.Stores.FirstOrDefault(d => d.IdStore == id);

            return View(detail);
        }
// GET: Store/CreateStore
        public ActionResult CreateStore(int? idstore)
        {
            ViewBag.PageName = idstore == null ? "Create New Store" : "Edit Store";
            ViewBag.isEdit = idstore == null ? false : true;

            if(idstore == null)
            {
                return View();
            }
            else
            {
                var storelist = _context.Stores.Find(idstore);

                if(storelist == null)
                {
                    NotFound();
                }

                return PartialView("_EditOrCreate",storelist);
            }
        }

        // POST: Store/CreateStore
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateStore(int idstore,[Bind("IdStore,NameStore,Location,QuantityArticles,NewArticles,State")] 
                Store stores )
        {
            bool ExitStore = false;

            Store store1 = _context.Stores.Find(idstore);

            if(store1 != null)
            {
                ExitStore = true;
            }
            else
            {
                store1 = new Store();
            }
             

            if (ModelState.IsValid)
            {
                try
                {
                    store1.NameStore = stores.NameStore;
                    store1.Location = stores.Location;
                    store1.QuantityArticles = stores.QuantityArticles;
                    store1.NewArticles = stores.NewArticles;

                    if (ExitStore)
                    {
                        _context.Update(store1);
                    }
                    else
                    {
                        _context.Add(store1);
                    }
                    
                    _context.SaveChanges();

                }
                catch (DbUpdateException)
                {

                    return View();
                }

                return RedirectToAction(nameof(ListStores));

            }

            return View(stores);
        }


        //GET: Store/Delete/5
        public ActionResult Delete(int? id)
        {
            var storea =  _context.Stores
                .Include(e=>e.Inventories)
                .Single(i=>i.IdStore == id);

            var inve = _context.Inventories
                .Where(i => i.FkStore == id)
                .ToList();
            inve.ForEach(i => i.FkStore = null);

            _context.Stores.Remove(storea);
            //storea.Inventories.Clear();
            _context.SaveChanges();

            return RedirectToAction(nameof(ListStores));
           
        }

        // POST: Store/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int? id)
        {

            return View();
            
        }
    }

    
}

Odontogest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Odontogest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- ===== Plugin CSS ===== -->
    <link href="~/plugins/components/chartist-js/dist/chartist.min.css" rel="stylesheet">
    <link href="~/plugins/components/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css" rel="stylesheet">
    <link href="~/plugins/components/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="~/plugins/components/dropify/dist/css/dropify.min.css" rel="stylesheet">
    <!-- ===== Animation CSS ===== -->
    <link href="~/css/animate.css" rel="stylesheet">
    <!-- ===== Custom CSS ===== -->
    <link href="~/css/site.css" rel="stylesheet">
    <!-- ===== Color CSS ===== -->
    <link href="~/css/colors/blue.css" id="theme" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Odontogest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="ListInventory">List Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="ListStores">List Store</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="ListCategory">List Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now - Odontogest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <!-- ===== jQuery ===== -->
    <script src="~/plugins/components/jquery/dist/jquery.min.js"></script>
    <!-- ===== Bootstrap JavaScript ===== -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src=""></script>
    <!-- ===== Slimscroll JavaScript ===== -->
    <script src="~/js/jquery.slimscroll.js"></script>
    <!-- ===== Wave Effects JavaScript ===== -->
    <script src="~/js/waves.js"></script>
    <!-- ===== Menu Plugin JavaScript ===== -->
    <script src="~/js/sidebarmenu.js"></script>
    <!-- ===== Custom JavaScript ===== -->
    <script src="~/js/custom.js"></script>
    <script src="~/plugins/components/datatables/jquery.dataTables.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/plugins/components/chartist-js/dist/chartist.min.js"></script>
    <script src="~/plugins/components/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="~/plugins/components/styleswitcher/jQuery.style.switcher.js"></script>
    <script src="~/plugins/components/sparkline/jquery.sparkline.min.js"></script>
    <script src="~/plugins/components/sparkline/jquery.charts-sparkline.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>